#ifndef	__LED_H
#define __LED_H



#define RGB_TEST_LED(x)		x?HAL_GPIO_WritePin(RGB_TEST_LED_PORT, RGB_TEST_LED_PIN, GPIO_PIN_SET):\
														HAL_GPIO_WritePin(RGB_TEST_LED_PORT, RGB_TEST_LED_PIN, GPIO_PIN_RESET)
#define RGB_TEST_LED_TOL()  HAL_GPIO_TogglePin(RGB_TEST_LED_PORT,RGB_TEST_LED_PIN)


#define KEY_TEST_LED(x)		x?HAL_GPIO_WritePin(KEY_TEST_LED_PORT, KEY_TEST_LED_PIN, GPIO_PIN_SET):\
														HAL_GPIO_WritePin(KEY_TEST_LED_PORT, KEY_TEST_LED_PIN, GPIO_PIN_RESET)
#define KEY_TEST_LED_TOL()  HAL_GPIO_TogglePin(KEY_TEST_LED_PORT,KEY_TEST_LED_PIN)														
														

#define MMA_TEST_LED(x)		x?HAL_GPIO_WritePin(MMA_TEST_LED_PORT, MMA_TEST_LED_PIN, GPIO_PIN_SET):\
														HAL_GPIO_WritePin(MMA_TEST_LED_PORT, MMA_TEST_LED_PIN, GPIO_PIN_RESET)
#define MMA_TEST_LED_TOL()  HAL_GPIO_TogglePin(MMA_TEST_LED_PORT,MMA_TEST_LED_PIN)	

#define GYR_TEST_LED(x)		x?HAL_GPIO_WritePin(GYR_TEST_LED_PORT, GYR_TEST_LED_PIN, GPIO_PIN_SET):\
														HAL_GPIO_WritePin(GYR_TEST_LED_PORT, GYR_TEST_LED_PIN, GPIO_PIN_RESET)
#define GYR_TEST_LED_TOL()  HAL_GPIO_TogglePin(GYR_TEST_LED_PORT,GYR_TEST_LED_PIN)



#define KEY_BORAD_LED(x)	x?HAL_GPIO_WritePin(KEY_BORAD_LED_PORT, KEY_BORAD_LED_PIN, GPIO_PIN_SET):\
														HAL_GPIO_WritePin(KEY_BORAD_LED_PORT, KEY_BORAD_LED_PIN, GPIO_PIN_RESET)
#define KEY_BORAD_LED_TOL() HAL_GPIO_TogglePin(KEY_BORAD_LED_PORT,KEY_BORAD_LED_PIN)

#define SGM_1V8_EN(x)			x?HAL_GPIO_WritePin(SGM_1V8_EN_PORT, SGM_1V8_EN_PIN, GPIO_PIN_SET):\
														HAL_GPIO_WritePin(SGM_1V8_EN_PORT, SGM_1V8_EN_PIN, GPIO_PIN_RESET)

#endif










